/**
 * PetServicesIndia — Data Layer
 * All listing data, taxonomies, and city metadata.
 * To add a new city: add to CITIES object and add listings with city: 'newcity'
 * To add a new listing: push a new object into LISTINGS following the schema below.
 */

var PSD = (function () {
  'use strict';

  /* =========================================================
     CATEGORIES
     ========================================================= */
  var CATEGORIES = {
    vets:     { label: 'Vets & Hospitals',  icon: '🩺', color: 'vet'      },
    trainers: { label: 'Dog Trainers',       icon: '🐕', color: 'trainer'  },
    groomers: { label: 'Pet Groomers',       icon: '✂️', color: 'groomer'  },
    boarding: { label: 'Pet Boarding',       icon: '🏨', color: 'boarding' },
    petfood:  { label: 'Pet Food & Shops',  icon: '🛒', color: 'petfood'  }
  };

  /* =========================================================
     BREED TAGS
     ========================================================= */
  var BREED_TAGS = [
    { value: 'all',        label: 'All Breeds',        icon: '🐾' },
    { value: 'small',      label: 'Small Breeds',      icon: '🐩' },
    { value: 'large',      label: 'Large Breeds',      icon: '🦮' },
    { value: 'aggressive', label: 'Aggressive / Reactive', icon: '⚡' },
    { value: 'puppy',      label: 'Puppies',           icon: '🐶' }
  ];

  /* =========================================================
     CITIES
     active: true  = has data, shown in selector
     active: false = coming soon, shown greyed in footer/cities section
     ========================================================= */
  var CITIES = {
    mumbai:    { name: 'Mumbai',    state: 'Maharashtra', emoji: '🌊', active: true },
    assam:     { name: 'Assam',     state: 'Assam',       emoji: '🍵', active: true },
    delhi:     { name: 'Delhi',     state: 'Delhi',       emoji: '🕌', active: false },
    bangalore: { name: 'Bangalore', state: 'Karnataka',   emoji: '🌿', active: true },
    pune:      { name: 'Pune',      state: 'Maharashtra', emoji: '🏔️', active: false },
    chennai:   { name: 'Chennai',   state: 'Tamil Nadu',  emoji: '🌴', active: false },
    hyderabad: { name: 'Hyderabad', state: 'Telangana',   emoji: '💎', active: false },
    kolkata:   { name: 'Kolkata',   state: 'West Bengal', emoji: '🎨', active: false },
    jaipur:    { name: 'Jaipur',    state: 'Rajasthan',   emoji: '🏰', active: false }
  };

  /* =========================================================
     LISTINGS
     Schema per listing:
     {
       id:          string   unique slug
       rank:        number   position within category (1 = top)
       name:        string   display name
       city:        string   key in CITIES
       category:    string   key in CATEGORIES
       description: string   1–2 sentences about the service
       area:        string   neighbourhood / locality
       address:     string   full address (blank = TBD)
       phone:       string   contact number (blank = TBD)
       website:     string   full URL including https://
       websiteLabel:string   display label for website link
       specialty:   string   short specialty/features summary
       badges:      string[] badge keys: 'emergency','247','premium','at-home',
                             'cage-free','budget','certified','mobile','award',
                             'organic','multi-location'
       breeds:      string[] from BREED_TAGS values ('all','small','large','aggressive','puppy')
     }
     ========================================================= */
  var LISTINGS = [

    /* --------------------------------------------------------
       VETERINARY CLINICS / HOSPITALS — MUMBAI
       -------------------------------------------------------- */
    {
      id: 'blue-7-vets',
      rank: 1,
      name: 'Blue 7 Vets',
      city: 'mumbai',
      category: 'vets',
      description: '24×7 emergency multi-specialty veterinary hospital with state-of-the-art diagnostics, ICU care, and surgical facilities. One of Mumbai\'s most trusted emergency care centres for pets.',
      area: 'Altamount Road (Opp. Antilia)',
      address: 'Altamount Road, Cumballa Hill, Mumbai 400026',
      phone: '',
      website: 'https://blue7vets.com',
      websiteLabel: 'blue7vets.com',
      specialty: 'Emergency & Multi-Specialty',
      badges: ['247', 'emergency'],
      breeds: ['all']
    },
    {
      id: 'dr-nilimas-clinic',
      rank: 2,
      name: "Dr. Nilima's Veterinary Clinic",
      city: 'mumbai',
      category: 'vets',
      description: 'Dr. Nilima Paranjpe brings over 31 years of veterinary experience to this well-established clinic. A trusted name among Mumbai pet owners for decades of compassionate care.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://threebestrated.in',
      websiteLabel: 'threebestrated.in',
      specialty: 'General Practice — 31 Years Experience',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'paw-prints-vet',
      rank: 3,
      name: 'Paw Prints Veterinary Clinic',
      city: 'mumbai',
      category: 'vets',
      description: 'Full-service clinic offering advanced diagnostics including radiology, laboratory testing, cardiology, and orthopaedic surgeries. Comprehensive care under one roof in Goregaon West.',
      area: 'Goregaon West',
      address: 'Goregaon West, Mumbai',
      phone: '',
      website: 'https://threebestrated.in',
      websiteLabel: 'threebestrated.in',
      specialty: 'Radiology, Cardiology, Orthopaedics',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'crown-vet',
      rank: 4,
      name: 'Crown Vet',
      city: 'mumbai',
      category: 'vets',
      description: 'International-standard veterinary facility providing a full spectrum of care from dental treatment to advanced radiology. Known for its high clinical standards and modern equipment.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://travenix.com',
      websiteLabel: 'travenix.com',
      specialty: 'International Standards — Dental & Radiology',
      badges: ['premium'],
      breeds: ['all']
    },
    {
      id: 'acumed-vet',
      rank: 5,
      name: 'AcuMed Veterinary Specialty',
      city: 'mumbai',
      category: 'vets',
      description: 'Specialty veterinary centre in Kandivali East focusing on advanced neurology, ECG, and cardiac care for pets. Ideal for complex cases requiring specialist attention.',
      area: 'Kandivali East',
      address: 'Kandivali East, Mumbai',
      phone: '',
      website: 'https://travenix.com',
      websiteLabel: 'travenix.com',
      specialty: 'Neurology, ECG, Cardiac Care',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'top-dog-pets-clinic',
      rank: 6,
      name: 'Top Dog Pets Clinic',
      city: 'mumbai',
      category: 'vets',
      description: 'Andheri West clinic led by the experienced Dr. M.S. Chousalkar, offering advanced laparoscopic surgeries and comprehensive veterinary services for all breeds.',
      area: 'Andheri West',
      address: 'Andheri West, Mumbai',
      phone: '',
      website: 'https://travenix.com',
      websiteLabel: 'travenix.com',
      specialty: 'Laparoscopic Surgery',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'vetic-pet-clinics',
      rank: 7,
      name: 'Vetic Pet Clinics',
      city: 'mumbai',
      category: 'vets',
      description: 'A growing chain of modern pet clinics across multiple Mumbai locations with in-house labs, surgery suites, pharmacy, and telemedicine support. Consistent, tech-forward care.',
      area: 'Multiple Locations',
      address: 'Multiple Locations, Mumbai',
      phone: '',
      website: 'https://vetic.in',
      websiteLabel: 'vetic.in',
      specialty: 'In-House Labs, Surgery, Multi-Location',
      badges: ['multi-location'],
      breeds: ['all']
    },
    {
      id: 'dr-khushis-pet-clinic',
      rank: 8,
      name: "Dr. Khushi's Pet Clinic",
      city: 'mumbai',
      category: 'vets',
      description: 'A warm, approachable veterinary clinic in Mumbai providing compassionate general practice care for dogs, cats, and small animals. Bookable online via Practo.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://practo.com',
      websiteLabel: 'practo.com',
      specialty: 'General Practice',
      badges: [],
      breeds: ['all']
    },

    /* --------------------------------------------------------
       DOG TRAINERS — MUMBAI
       -------------------------------------------------------- */
    {
      id: 'k9-school',
      rank: 1,
      name: 'K9 School (Adnan Khan)',
      city: 'mumbai',
      category: 'trainers',
      description: "Mumbai's leading professional dog training institution run by Adnan Khan. Structured programs covering obedience, behavior modification, and socialization for all breeds and ages.",
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://k9school.in',
      websiteLabel: 'k9school.in',
      specialty: 'Obedience, Behavior Modification',
      badges: ['certified'],
      breeds: ['all', 'puppy']
    },
    {
      id: 'nilesh-narvekar',
      rank: 2,
      name: 'Nilesh Narvekar',
      city: 'mumbai',
      category: 'trainers',
      description: 'Highly decorated trainer with 21 years of experience and 3000+ dogs trained. Best Handler Award winner. Specializes in obedience, agility, and behavioral training across breeds.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://dogtrainerinmumbai.com',
      websiteLabel: 'dogtrainerinmumbai.com',
      specialty: 'Obedience, Agility, Behaviour',
      badges: ['award', 'certified'],
      breeds: ['all', 'large']
    },
    {
      id: 'action-dogs-services',
      rank: 3,
      name: 'Action Dogs Services (Raghav Shukla)',
      city: 'mumbai',
      category: 'trainers',
      description: '20 years of professional dog training spanning 6 states. INKC & KCI certified trainer specializing in protection, guard dogs, and advanced obedience training.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://actiondogsservices.com',
      websiteLabel: 'actiondogsservices.com',
      specialty: 'Protection, Guard Dogs, Basic/Advanced',
      badges: ['certified'],
      breeds: ['all', 'large', 'aggressive']
    },
    {
      id: 'rohini-fernandes',
      rank: 4,
      name: 'Rohini Fernandes',
      city: 'mumbai',
      category: 'trainers',
      description: "Runs 'Naughty Boys' (aggressive dog specialist program) and Pawfect Classes. Known for her patience and results with reactive, aggressive, and difficult-to-train dogs.",
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'lbb.in',
      specialty: 'Aggression, Basic Training',
      badges: [],
      breeds: ['all', 'aggressive']
    },
    {
      id: 'tanya-patel',
      rank: 5,
      name: 'Tanya Patel',
      city: 'mumbai',
      category: 'trainers',
      description: 'Khar-based dog trainer specializing in obedience and aggression management. Uses positive reinforcement techniques to correct behavioral issues efficiently.',
      area: 'Khar, Mumbai',
      address: 'Khar, Mumbai',
      phone: '',
      website: 'https://zeezest.com',
      websiteLabel: 'zeezest.com',
      specialty: 'Obedience, Behavior Modification',
      badges: [],
      breeds: ['all', 'aggressive']
    },
    {
      id: 'saket-gokhale',
      rank: 6,
      name: 'Saket Gokhale',
      city: 'mumbai',
      category: 'trainers',
      description: 'Offers personalized in-home training programs for fearful and aggressive dogs. Expert in building confidence in anxious pets using science-based, force-free methods.',
      area: 'Mumbai (In-Home)',
      address: 'Mumbai (home visits)',
      phone: '',
      website: 'https://zeezest.com',
      websiteLabel: 'zeezest.com',
      specialty: 'In-Home, Fearful & Aggressive Dogs',
      badges: ['at-home'],
      breeds: ['all', 'aggressive']
    },
    {
      id: 'delano-tracy',
      rank: 7,
      name: 'Delano & Tracy',
      city: 'mumbai',
      category: 'trainers',
      description: 'Highly recommended certified behaviorists with deep expertise in behavior modification and aggression rehabilitation. Trusted by dog owners across Mumbai for complex cases.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://dogstrainingindia.com',
      websiteLabel: 'dogstrainingindia.com',
      specialty: 'Behaviour, Aggression',
      badges: ['certified'],
      breeds: ['all', 'aggressive']
    },
    {
      id: 'paw-station',
      rank: 8,
      name: 'Paw Station',
      city: 'mumbai',
      category: 'trainers',
      description: 'Customized training programs for aggression, anxiety, and general obedience. Offers dedicated puppy starter classes as well as adult dog programs for all temperaments.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://starofservice.in',
      websiteLabel: 'starofservice.in',
      specialty: 'Puppy & Adult Classes, Aggression, Anxiety',
      badges: [],
      breeds: ['all', 'aggressive', 'puppy']
    },

    /* --------------------------------------------------------
       PET GROOMERS — MUMBAI
       -------------------------------------------------------- */
    {
      id: 'fur-n-tails',
      rank: 1,
      name: 'Fur N Tails',
      city: 'mumbai',
      category: 'groomers',
      description: 'Professional salon with certified staff delivering hygienic, stress-free full grooming services. Known for careful handling and consistent quality across all coat types and sizes.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'lbb.in',
      specialty: 'Full Grooming, Certified Staff',
      badges: ['certified'],
      breeds: ['all']
    },
    {
      id: 'pet-pamper',
      rank: 2,
      name: 'Pet Pamper',
      city: 'mumbai',
      category: 'groomers',
      description: 'Internationally licensed grooming salon using premium imported products. Also offers grooming certification courses for aspiring professional groomers.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'lbb.in',
      specialty: 'Grooming + Grooming Courses',
      badges: ['premium', 'certified'],
      breeds: ['all', 'small']
    },
    {
      id: 'pet-grooming-tales',
      rank: 3,
      name: 'Pet Grooming Tales (Yashwini Shetty)',
      city: 'mumbai',
      category: 'groomers',
      description: 'Award-winning internationally licensed groomer specializing in breed-standard show cuts. Yashwini Shetty has trained in grooming competitions and delivers salon-quality results.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'lbb.in',
      specialty: 'Show Grooming, Award-Winning',
      badges: ['award', 'certified'],
      breeds: ['all', 'small']
    },
    {
      id: 'doggie-dog-world-groomer',
      rank: 4,
      name: 'Doggie Dog World',
      city: 'mumbai',
      category: 'groomers',
      description: 'Full-service grooming facility with an added swimming pool for hydrotherapy and play. Also offers training and pet communication sessions alongside standard grooming packages.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'lbb.in',
      specialty: 'Full Service, Swimming Pool',
      badges: [],
      breeds: ['all', 'large']
    },
    {
      id: 'thepetnest-groomer',
      rank: 5,
      name: 'ThePetNest',
      city: 'mumbai',
      category: 'groomers',
      description: 'Home grooming service where trained, vetted professional groomers come to your doorstep. Covers multiple premium Mumbai neighbourhoods. Stress-free for pets who dislike salons.',
      area: 'Multiple Areas, Mumbai',
      address: 'Multiple Areas, Mumbai',
      phone: '',
      website: 'https://thepetnest.com',
      websiteLabel: 'thepetnest.com',
      specialty: 'At-Home Grooming, Multi-Area',
      badges: ['at-home'],
      breeds: ['all']
    },
    {
      id: 'patmypets',
      rank: 6,
      name: 'Patmypets',
      city: 'mumbai',
      category: 'groomers',
      description: 'Convenient at-home pet grooming service across Mumbai. Easy online booking with experienced groomers coming to your location at your preferred time.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://patmypets.com',
      websiteLabel: 'patmypets.com',
      specialty: 'At-Home Grooming, Online Booking',
      badges: ['at-home'],
      breeds: ['all']
    },
    {
      id: 'oh-my-pet-grooming',
      rank: 7,
      name: 'Oh My Pet Grooming',
      city: 'mumbai',
      category: 'groomers',
      description: 'At-home spa grooming experience with same-day availability in select Mumbai areas. Experienced groomers deliver a full bath-and-groom package in the comfort of your home.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://ohmypetgrooming.in',
      websiteLabel: 'ohmypetgrooming.in',
      specialty: 'At-Home Spa, Same-Day Availability',
      badges: ['at-home', 'premium'],
      breeds: ['all', 'small']
    },
    {
      id: 'flying-fur',
      rank: 8,
      name: 'Flying Fur',
      city: 'mumbai',
      category: 'groomers',
      description: 'Innovative mobile grooming van that parks at your location. Full professional grooming equipment on wheels — ideal for pets who are stressed by travel or salon environments.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://flyingfur.in',
      websiteLabel: 'flyingfur.in',
      specialty: 'Mobile Grooming Van',
      badges: ['mobile', 'at-home'],
      breeds: ['all', 'small']
    },

    /* --------------------------------------------------------
       PET BOARDING / HOSTELS — MUMBAI
       -------------------------------------------------------- */
    {
      id: 'petfelix',
      rank: 1,
      name: 'PetFelix',
      city: 'mumbai',
      category: 'boarding',
      description: 'Premium 6,400 sq ft pet resort with individual 50 sq ft air-conditioned rooms, a 2,000 sq ft play area, and an exceptional 6:1 dog-to-staff ratio. Mumbai\'s most spacious boarding facility.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://petfelix.com',
      websiteLabel: 'petfelix.com',
      specialty: 'AC Rooms, 6:1 Staff Ratio, Play Area',
      badges: ['premium'],
      breeds: ['all', 'large', 'small']
    },
    {
      id: 'pupstop',
      rank: 2,
      name: 'Pupstop',
      city: 'mumbai',
      category: 'boarding',
      description: 'Budget-friendly daycare and overnight boarding service with over 6 years of experience. 24×7 on-site veterinary support ensures your pet is always in safe hands.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://pupstop.in',
      websiteLabel: 'pupstop.in',
      specialty: 'Daycare, Overnight, 24/7 Vet',
      badges: ['budget', '247'],
      breeds: ['all']
    },
    {
      id: 'woof-n-goof',
      rank: 3,
      name: 'Woof N Goof Pet Resort',
      city: 'mumbai',
      category: 'boarding',
      description: 'Full-service pet resort in Thane with a swimming pool, grooming facility, dog training, and birthday party packages. A true resort experience for your fur baby.',
      area: 'Thane',
      address: 'Thane, Mumbai Metropolitan Region',
      phone: '',
      website: 'https://woofngoof.com',
      websiteLabel: 'woofngoof.com',
      specialty: 'Swimming Pool, Grooming, Training, Birthday Parties',
      badges: ['premium'],
      breeds: ['all', 'large']
    },
    {
      id: 'furends-pet-studio',
      rank: 4,
      name: 'Furends Pet Studio',
      city: 'mumbai',
      category: 'boarding',
      description: 'Luxurious boutique boarding studio designed to give your pet a genuine home-away-from-home experience. Premium facilities with personalized attention for each guest.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://furendspetstudio.com',
      websiteLabel: 'furendspetstudio.com',
      specialty: 'Luxurious, Home-Away-from-Home',
      badges: ['premium'],
      breeds: ['all']
    },
    {
      id: 'bonehemian-tails',
      rank: 5,
      name: 'Bonehemian Tails',
      city: 'mumbai',
      category: 'boarding',
      description: 'Cage-free daycare and boarding with a spacious off-leash play area. Perfect for social dogs who thrive in an open, free-roaming environment without the stress of a crate.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://bonehemiantails.com',
      websiteLabel: 'bonehemiantails.com',
      specialty: 'Cage-Free, Off-Leash Play',
      badges: ['cage-free'],
      breeds: ['all']
    },
    {
      id: 'petsitterz',
      rank: 6,
      name: 'Petsitterz (Dr. Neeta Vanjari)',
      city: 'mumbai',
      category: 'boarding',
      description: 'Exclusive one-pet-at-a-time boarding by veterinarian Dr. Neeta Vanjari in Oshiwara. Accepts both dogs and cats. Maximum personal attention guaranteed — truly personalized care.',
      area: 'Oshiwara, Mumbai',
      address: 'Oshiwara, Andheri West, Mumbai',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'lbb.in',
      specialty: 'One Pet at a Time, Vet-Led, Dogs & Cats',
      badges: ['premium'],
      breeds: ['all']
    },
    {
      id: 'doggie-dog-world-boarding',
      rank: 7,
      name: 'Doggie Dog World',
      city: 'mumbai',
      category: 'boarding',
      description: 'Comfortable boarding in Andheri West with individual cubicles and a swimming pool. Also offers daycare and grooming services making it a convenient all-in-one destination.',
      area: 'Andheri West',
      address: 'Andheri West, Mumbai',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'lbb.in',
      specialty: 'Daycare, Cubicles, Swimming Pool',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'pawfect-life',
      rank: 8,
      name: 'Pawfect Life (Niharika)',
      city: 'mumbai',
      category: 'boarding',
      description: "Niharika's cozy, home-like pet boarding in Andheri East. Small, intimate setting ideal for pets who prefer a quiet home environment over large kennel facilities.",
      area: 'Andheri East',
      address: 'Andheri East, Mumbai',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'lbb.in',
      specialty: 'Home-Like Environment, Andheri East',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'thepetnest-boarding',
      rank: 9,
      name: 'ThePetNest',
      city: 'mumbai',
      category: 'boarding',
      description: 'Curated network of vetted home-based pet sitters spread across multiple premium Mumbai localities. Each sitter is background-verified and pet-care trained.',
      area: 'Multiple Areas, Mumbai',
      address: 'Multiple Areas, Mumbai',
      phone: '',
      website: 'https://thepetnest.com',
      websiteLabel: 'thepetnest.com',
      specialty: 'Vetted Sitters, Multiple Premium Locations',
      badges: ['multi-location'],
      breeds: ['all']
    },
    {
      id: 'petbacker',
      rank: 10,
      name: 'PetBacker',
      city: 'mumbai',
      category: 'boarding',
      description: 'Platform aggregating 334+ boarding services across Mumbai with verified reviews and insurance coverage. Browse, compare, and book from a wide variety of boarding options.',
      area: 'Mumbai-Wide',
      address: 'Platform — serving all of Mumbai',
      phone: '',
      website: 'https://petbacker.in',
      websiteLabel: 'petbacker.in',
      specialty: '334+ Services, Reviews & Insurance',
      badges: ['multi-location'],
      breeds: ['all']
    },

    /* --------------------------------------------------------
       PET FOOD STORES / PET SHOPS — MUMBAI
       -------------------------------------------------------- */
    {
      id: 'huft',
      rank: 1,
      name: 'Heads Up For Tails (HUFT)',
      city: 'mumbai',
      category: 'petfood',
      description: "India's most popular premium pet retail chain with 100+ stores nationwide. Stocks a wide range of pet food, accessories, toys, and grooming products. Multiple Mumbai locations.",
      area: 'Multiple Locations',
      address: 'Multiple Locations across Mumbai',
      phone: '',
      website: 'https://headsupfortails.com',
      websiteLabel: 'headsupfortails.com',
      specialty: 'Chain Store — Food, Toys, Accessories, Grooming',
      badges: ['premium', 'multi-location'],
      breeds: ['all']
    },
    {
      id: 'mumbai-pet-shop',
      rank: 2,
      name: 'Mumbai Pet Shop',
      city: 'mumbai',
      category: 'petfood',
      description: 'Affordable one-stop pet shop in Andheri West stocking pet food, accessories, and a wide range of dog and cat items. Popular among local pet owners for competitive pricing.',
      area: 'Andheri West',
      address: 'Andheri West, Mumbai',
      phone: '',
      website: 'https://threebestrated.in',
      websiteLabel: 'threebestrated.in',
      specialty: 'Food, Accessories, Affordable Prices',
      badges: ['budget'],
      breeds: ['all']
    },
    {
      id: 'pets-barn',
      rank: 3,
      name: 'PetsBARN',
      city: 'mumbai',
      category: 'petfood',
      description: 'Lokhandwala\'s go-to store for organic and natural pet food. Stocks quality cat and dog foods, toys, treats, and bedding. Focuses on healthy, chemical-free options.',
      area: 'Lokhandwala',
      address: 'Lokhandwala Complex, Mumbai',
      phone: '',
      website: 'https://threebestrated.in',
      websiteLabel: 'threebestrated.in',
      specialty: 'Organic Food, Toys, Treats, Bedding',
      badges: ['organic'],
      breeds: ['all']
    },
    {
      id: 'oscar-pets-world',
      rank: 4,
      name: "Oscar Pet's World",
      city: 'mumbai',
      category: 'petfood',
      description: 'Government-certified multi-service pet store chain offering puppy sales, food, accessories, boarding, and basic training across multiple locations in Mumbai.',
      area: 'Multiple Locations',
      address: 'Multiple Locations, Mumbai',
      phone: '',
      website: 'https://threebestrated.in',
      websiteLabel: 'threebestrated.in',
      specialty: 'Govt Certified — Puppy Sales, Lodging, Training',
      badges: ['certified', 'multi-location'],
      breeds: ['all', 'puppy']
    },
    {
      id: 'apsans',
      rank: 5,
      name: "Apsan's",
      city: 'mumbai',
      category: 'petfood',
      description: 'Three-gala store known for its comprehensive range including special prescription food, medicine, crates, leashes, and allergy-specific diets. A specialist destination for pet nutrition.',
      area: 'Mumbai',
      address: 'Mumbai (3 locations)',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'lbb.in',
      specialty: 'Allergy-Specific Food, Medicine, Wide Range',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'shake-hands',
      rank: 6,
      name: 'Shake Hands',
      city: 'mumbai',
      category: 'petfood',
      description: 'Tardeo-based specialty store stocking health supplements, treats for dogs and cats, and vet-recommended foods. A trusted source for nutritional and therapeutic pet products.',
      area: 'Tardeo',
      address: 'Tardeo, Mumbai',
      phone: '',
      website: 'https://shakehands.co.in',
      websiteLabel: 'shakehands.co.in',
      specialty: 'Health Supplements, Vet Foods, Specialty Nutrition',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'ohh-my-dog-cafe-pefe',
      rank: 7,
      name: 'Ohh My Dog + Cafe PeFe',
      city: 'mumbai',
      category: 'petfood',
      description: 'Unique hybrid concept: a fully stocked pet accessories and gear shop combined with a pet-friendly café. Shop for your dog, then enjoy a coffee together — truly pet inclusive.',
      area: 'Mumbai',
      address: 'Mumbai',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'lbb.in',
      specialty: 'Pet Shop + Pet-Friendly Cafe',
      badges: ['premium'],
      breeds: ['all']
    },
    {
      id: 'pet-food-court',
      rank: 8,
      name: 'Pet Food Court',
      city: 'mumbai',
      category: 'petfood',
      description: 'Comprehensive pet food store in Andheri East with a wide selection of dry and wet food for cats and dogs, along with fish food and bird seed for exotic pet owners.',
      area: 'Andheri East',
      address: 'Andheri East, Mumbai',
      phone: '',
      website: 'https://travenix.com',
      websiteLabel: 'travenix.com',
      specialty: 'Dry & Wet Food, Treats, Fish, Bird Supplies',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'paws-n-furs',
      rank: 9,
      name: "Paws 'n' Furs",
      city: 'mumbai',
      category: 'petfood',
      description: 'Bandra institution with over 20 years of serving Mumbai\'s pet community. Stocks nutritious food, grooming products, accessories, and everything else your pet needs.',
      area: 'Bandra',
      address: 'Bandra, Mumbai',
      phone: '',
      website: 'https://knocksense.com',
      websiteLabel: 'knocksense.com',
      specialty: '20+ Years, Food, Grooming Products',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'posh-pets',
      rank: 10,
      name: 'Posh Pets',
      city: 'mumbai',
      category: 'petfood',
      description: 'Curated boutique pet shop in Bandra West specializing in rare indie brands, gluten-free food options, and premium grooming services. Perfect for discerning pet parents.',
      area: 'Bandra West',
      address: 'Bandra West, Mumbai',
      phone: '',
      website: 'https://knocksense.com',
      websiteLabel: 'knocksense.com',
      specialty: 'Indie Brands, Gluten-Free, Grooming',
      badges: ['premium'],
      breeds: ['all', 'small']
    },

    /* ========================================================
       ========================================================
       ASSAM — ALL CATEGORIES
       ========================================================
       ======================================================== */

    /* --------------------------------------------------------
       VETERINARY CLINICS / HOSPITALS — ASSAM
       -------------------------------------------------------- */
    {
      id: 'max-veterinary-clinic-guwahati',
      rank: 1,
      name: 'Max Veterinary Clinic',
      city: 'assam',
      category: 'vets',
      description: 'Over 9 years of service on G.S. Road. Full-range facility offering vaccination, anesthesia, ultrasound, ECG, X-ray, blood tests, pathology, digital ray laser therapy, surgeries, dental checkups, and pet grooming.',
      area: 'Khanapara, Guwahati',
      address: 'Dutta Building, G.S. Road, Khanapara, Guwahati-22',
      phone: '',
      website: 'https://maxvetclinic.com',
      websiteLabel: 'maxvetclinic.com',
      specialty: 'Full Diagnostics, Surgeries, Dental, Laser Therapy',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'pet-care-unit-guwahati',
      rank: 2,
      name: 'Pet Care Unit',
      city: 'assam',
      category: 'vets',
      description: 'Well-equipped veterinary facility in Jalukbari offering vaccination, dentistry, weight management, ultrasound, anesthesia, nutrition diet, spaying/neutering, senior pet care, dermatology, and endoscopy.',
      area: 'Jalukbari, Guwahati',
      address: 'AEC Road, Gopinath Bordoloi Nagar, Jalukbari, Guwahati',
      phone: '',
      website: 'https://lybrate.com',
      websiteLabel: 'Lybrate',
      specialty: 'Dentistry, Endoscopy, Dermatology, Senior Pet Care',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'star-pets-guwahati',
      rank: 3,
      name: 'STAR PETS \u2013 The Veterinary Clinic',
      city: 'assam',
      category: 'vets',
      description: 'Zoo Road area clinic offering pet grooming, vaccinations, surgeries, and a selection of pet supplies all under one roof.',
      area: 'Zoo Road, Guwahati',
      address: 'Zoo Road area, Guwahati',
      phone: '',
      website: 'https://justdial.com',
      websiteLabel: 'Justdial',
      specialty: 'Grooming, Vaccinations, Surgeries, Pet Supplies',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'dolphin-aquarium-vet',
      rank: 4,
      name: 'Dolphin Aquarium Pet Shop & Veterinary Clinic',
      city: 'assam',
      category: 'vets',
      description: 'Basistha Road facility providing medical check-ups, vaccinations, grooming, veterinary services, and a pet supply shop for all your pet needs.',
      area: 'Basisthpur, Guwahati',
      address: 'Basistha Road, Housefed, Basisthpur, Guwahati',
      phone: '',
      website: 'https://justdial.com',
      websiteLabel: 'Justdial',
      specialty: 'Check-ups, Vaccinations, Grooming, Pet Supplies',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'companions-vet-clinic',
      rank: 5,
      name: 'Companions Vet Clinic',
      city: 'assam',
      category: 'vets',
      description: 'Trusted veterinary clinic on Beltola-Basistha Road serving Guwahati pet owners with quality medical care, consultations, and preventive treatments.',
      area: 'Basisthpur, Guwahati',
      address: 'Beltola-Basistha Road Last Gate, Housefed, Basisthpur, Guwahati',
      phone: '',
      website: 'https://idbf.in',
      websiteLabel: 'idbf.in',
      specialty: 'General Veterinary Practice',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'nilay-pet-vet-hospital',
      rank: 6,
      name: 'Nilay & C/O Pet & Vet Hospital',
      city: 'assam',
      category: 'vets',
      description: 'Pet and veterinary hospital on Zoo Narengi Road offering consultations, treatments, and general veterinary care for dogs, cats, and small animals.',
      area: 'Zoo Narengi Road, Guwahati',
      address: 'Zoo Narengi Road, Guwahati',
      phone: '',
      website: 'https://justdial.com',
      websiteLabel: 'Justdial',
      specialty: 'General Veterinary Hospital',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'bharosa-pet-health-zone',
      rank: 7,
      name: 'BHAROSA The Pet Health Zone',
      city: 'assam',
      category: 'vets',
      description: 'Ghoramara-based pet health clinic offering affordable in-clinic consultations starting at \u20B9300. Focused on accessible, quality veterinary care for Guwahati pet owners.',
      area: 'Ghoramara, Guwahati',
      address: 'Ghoramara, Guwahati',
      phone: '',
      website: 'https://lybrate.com',
      websiteLabel: 'Lybrate',
      specialty: 'Affordable In-Clinic Consultations',
      badges: ['budget'],
      breeds: ['all']
    },
    {
      id: 'petmed-guwahati',
      rank: 8,
      name: 'PetMed Guwahati',
      city: 'assam',
      category: 'vets',
      description: 'Sundarpur-based clinic near RG Baruah Road offering home visit veterinary care and online consultations — perfect for pets stressed by clinic visits.',
      area: 'Sundarpur, Guwahati',
      address: 'Surujmukhi Path, RG Baruah Road, near Bharat Petrol Pump, Sundarpur',
      phone: '',
      website: 'https://idbf.in',
      websiteLabel: 'idbf.in',
      specialty: 'Home Visit Vet, Online Consultation',
      badges: ['at-home'],
      breeds: ['all']
    },
    {
      id: 'college-of-veterinary-science',
      rank: 9,
      name: 'College of Veterinary Science',
      city: 'assam',
      category: 'vets',
      description: 'Government veterinary college near Khanapara Bus Stop with modern diagnostic machinery and a clinical wing serving patients. A resource for complex cases requiring specialist care.',
      area: 'Khanapara, Guwahati',
      address: 'Near Khanapara Bus Stoppage, Guwahati',
      phone: '',
      website: '',
      websiteLabel: '',
      specialty: 'Government College, Modern Diagnostics',
      badges: ['certified'],
      breeds: ['all']
    },
    {
      id: 'govt-vet-hospitals-assam',
      rank: 10,
      name: 'Government Veterinary Hospitals',
      city: 'assam',
      category: 'vets',
      description: '570 veterinary hospitals and dispensaries across Assam run by the Department of Animal Husbandry & Veterinary. Affordable government-backed care available statewide.',
      area: 'Across Assam',
      address: 'Multiple locations across Assam (570 facilities)',
      phone: '',
      website: 'https://veterinary.assam.gov.in',
      websiteLabel: 'veterinary.assam.gov.in',
      specialty: '570 Hospitals Statewide, Govt Facility',
      badges: ['certified', 'multi-location', 'budget'],
      breeds: ['all']
    },

    /* --------------------------------------------------------
       DOG TRAINERS — ASSAM
       -------------------------------------------------------- */
    {
      id: 'k9-academy-guwahati',
      rank: 1,
      name: 'K9 Academy',
      city: 'assam',
      category: 'trainers',
      description: 'Expert dog training institute operating since 2017. Offers training, boarding, grooming, and a pet shop. Has trained 1,200+ dogs all over India, building stronger bonds between dogs and owners.',
      area: 'Guwahati',
      address: 'Guwahati, Assam',
      phone: '',
      website: 'https://k9academy.in',
      websiteLabel: 'k9academy.in',
      specialty: 'Training, Boarding, Grooming, Pet Shop',
      badges: ['certified'],
      breeds: ['all', 'large', 'puppy']
    },
    {
      id: 'singha-home-dog-training',
      rank: 2,
      name: 'Singha Home Dog Training',
      city: 'assam',
      category: 'trainers',
      description: "Guwahati's best in-home dog trainer offering one-on-one sessions without distractions. Specializes in behavioural therapy, aggression management, and obedience in your dog\u2019s own environment.",
      area: 'Guwahati',
      address: 'Guwahati, Assam (home visits)',
      phone: '',
      website: 'https://singhahomedogtraining.in',
      websiteLabel: 'singhahomedogtraining.in',
      specialty: 'In-Home One-on-One, Behavioural Therapy',
      badges: ['at-home'],
      breeds: ['all', 'aggressive']
    },
    {
      id: 'mr-n-mrs-pet-trainer-assam',
      rank: 3,
      name: 'Mr n Mrs Pet',
      city: 'assam',
      category: 'trainers',
      description: 'Home dog training services in Guwahati covering obedience, behaviour modification, guard dog training, and puppy toilet training. Convenient at-your-doorstep programs.',
      area: 'Guwahati',
      address: 'Guwahati, Assam',
      phone: '',
      website: 'https://mrnmrspet.com',
      websiteLabel: 'mrnmrspet.com',
      specialty: 'Obedience, Guard Training, Puppy Toilet Training',
      badges: ['at-home'],
      breeds: ['all', 'aggressive', 'puppy']
    },
    {
      id: 'thepetnest-trainer-assam',
      rank: 4,
      name: 'ThePetNest',
      city: 'assam',
      category: 'trainers',
      description: 'Online and in-home dog training programs in Guwahati by certified trainers. Uses positive reinforcement techniques for stress-free, effective learning.',
      area: 'Guwahati',
      address: 'Guwahati, Assam',
      phone: '',
      website: 'https://thepetnest.com/guwahati',
      websiteLabel: 'thepetnest.com',
      specialty: 'Online + Home Training, Positive Reinforcement',
      badges: ['at-home', 'certified'],
      breeds: ['all', 'puppy']
    },
    {
      id: 'nsfd-assam',
      rank: 5,
      name: 'National School for Dogs (NSFD)',
      city: 'assam',
      category: 'trainers',
      description: "India's largest dog training centre with 4,000+ dogs trained. ADPDT-certified trainers and expert animal behaviourists offer obedience, protection, sniffing, and guide dog courses.",
      area: 'India-wide (serves Assam)',
      address: 'Multiple centres across India',
      phone: '',
      website: 'https://nsfd.in',
      websiteLabel: 'nsfd.in',
      specialty: 'Obedience, Protection, Sniffing, Guide Dog Courses',
      badges: ['certified', 'award'],
      breeds: ['all', 'large', 'aggressive']
    },

    /* --------------------------------------------------------
       PET GROOMERS — ASSAM
       -------------------------------------------------------- */
    {
      id: 'interpet-grooming-salon',
      rank: 1,
      name: 'INTERPET Grooming Salon',
      city: 'assam',
      category: 'groomers',
      description: "First-of-its-kind dedicated grooming salon in Guwahati, located within the Veterinary Clinical Complex at Khanapara. Vet-approved professional grooming services with clinical-grade hygiene.",
      area: 'Khanapara, Guwahati',
      address: 'Veterinary Clinical Complex, Khanapara, Guwahati',
      phone: '',
      website: 'https://interpet.in',
      websiteLabel: 'interpet.in',
      specialty: 'Vet-Approved Salon, Clinical Complex',
      badges: ['certified', 'premium'],
      breeds: ['all']
    },
    {
      id: 'thepetnest-groomer-assam',
      rank: 2,
      name: 'ThePetNest',
      city: 'assam',
      category: 'groomers',
      description: 'Skilled professionals offering at-home dog clipping, grooming, and breed-specific styling (Shih Tzu haircuts, etc.). All groomers have 2+ years of experience and pass background checks.',
      area: 'Guwahati',
      address: 'Guwahati, Assam',
      phone: '',
      website: 'https://thepetnest.com/pet-grooming/guwahati',
      websiteLabel: 'thepetnest.com',
      specialty: 'At-Home, Breed-Specific Styling, Verified Staff',
      badges: ['at-home', 'certified'],
      breeds: ['all', 'small']
    },
    {
      id: 'mr-n-mrs-pet-groomer-assam',
      rank: 3,
      name: 'Mr n Mrs Pet',
      city: 'assam',
      category: 'groomers',
      description: 'Convenient home grooming service in Guwahati including bathing, hair cutting, nail clipping, and ear cleaning. No need to travel — groomers come to your doorstep.',
      area: 'Guwahati',
      address: 'Guwahati, Assam',
      phone: '',
      website: 'https://mrnmrspet.com',
      websiteLabel: 'mrnmrspet.com',
      specialty: 'Home Grooming — Bath, Haircut, Nail, Ear',
      badges: ['at-home'],
      breeds: ['all']
    },
    {
      id: 'petbacker-groomer-assam',
      rank: 4,
      name: 'PetBacker',
      city: 'assam',
      category: 'groomers',
      description: 'Platform to compare grooming services in Guwahati for the best prices. All services offered in a cage-free home environment, protected by insurance for your peace of mind.',
      area: 'Guwahati',
      address: 'Guwahati, Assam',
      phone: '',
      website: 'https://petbacker.in/dog-grooming/guwahati',
      websiteLabel: 'petbacker.in',
      specialty: 'Price Comparison, Cage-Free, Insured',
      badges: ['cage-free'],
      breeds: ['all']
    },
    {
      id: 'zoo-road-sundarpur-groomer',
      rank: 5,
      name: 'Zoo Road Sundarpur Groomer',
      city: 'assam',
      category: 'groomers',
      description: 'Highly rated grooming service (4.9 stars, 69 reviews) in the Zoo Road Sundarpur area. Offers pet grooming, pet care, and same-day service availability.',
      area: 'Zoo Road Sundarpur, Guwahati',
      address: 'Zoo Road Sundarpur, Guwahati',
      phone: '',
      website: 'https://justdial.com',
      websiteLabel: 'Justdial',
      specialty: 'Pet Grooming & Care, Same-Day Service',
      badges: ['award'],
      breeds: ['all']
    },
    {
      id: 'vip-road-six-mile-groomer',
      rank: 6,
      name: 'VIP Road Six Mile Groomer',
      city: 'assam',
      category: 'groomers',
      description: '7 years in pet healthcare with a solid 4.0 rating across 343 reviews. Experienced grooming professionals located in the Six Mile area on VIP Road.',
      area: 'VIP Road, Six Mile, Guwahati',
      address: 'VIP Road, Six Mile, Guwahati',
      phone: '',
      website: 'https://justdial.com',
      websiteLabel: 'Justdial',
      specialty: '7 Years Experience, 343 Reviews',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'k9-academy-groomer',
      rank: 7,
      name: 'K9 Academy',
      city: 'assam',
      category: 'groomers',
      description: 'Professional grooming services alongside their training and boarding facilities. Convenient one-stop destination for training, boarding, and grooming in Guwahati.',
      area: 'Guwahati',
      address: 'Guwahati, Assam',
      phone: '',
      website: 'https://k9academy.in',
      websiteLabel: 'k9academy.in',
      specialty: 'Grooming + Training + Boarding',
      badges: [],
      breeds: ['all']
    },

    /* --------------------------------------------------------
       PET BOARDING / HOSTELS — ASSAM
       -------------------------------------------------------- */
    {
      id: 'k9-academy-boarding',
      rank: 1,
      name: 'K9 Academy',
      city: 'assam',
      category: 'boarding',
      description: 'Safe, loving home away from home for your dog. Offers personalized care and attention with a cozy, secure boarding space while you\u2019re away. Includes training integration.',
      area: 'Guwahati',
      address: 'Guwahati, Assam',
      phone: '',
      website: 'https://k9academy.in',
      websiteLabel: 'k9academy.in',
      specialty: 'Personalized Boarding + Training',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'petbacker-guwahati',
      rank: 2,
      name: 'PetBacker Guwahati',
      city: 'assam',
      category: 'boarding',
      description: 'Cage-free home boarding via recommended sitters including Anant, Chaya, Subodh, Suranjana, and Moon. Includes payment protection, insurance, and 24\u00D77 platform support.',
      area: 'Guwahati',
      address: 'Multiple sitters across Guwahati',
      phone: '',
      website: 'https://petbacker.com/guwahati',
      websiteLabel: 'petbacker.com',
      specialty: 'Cage-Free Home Sitters, Insurance, 24/7 Support',
      badges: ['cage-free', 'multi-location'],
      breeds: ['all']
    },
    {
      id: 'thepetnest-boarding-assam',
      rank: 3,
      name: 'ThePetNest',
      city: 'assam',
      category: 'boarding',
      description: 'Dog and cat boarding facilities in Guwahati providing a safe, comfortable, fun environment for weekend getaways or longer stays. Vetted and verified host families.',
      area: 'Guwahati',
      address: 'Guwahati, Assam',
      phone: '',
      website: 'https://thepetnest.com/guwahati',
      websiteLabel: 'thepetnest.com',
      specialty: 'Dogs & Cats, Weekend & Long Stays',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'mr-n-mrs-pet-boarding-assam',
      rank: 4,
      name: 'Mr n Mrs Pet',
      city: 'assam',
      category: 'boarding',
      description: '5-star rated pet sitters offering insured and secured dog hostel, boarding, house sitting, and doggy day care services across Guwahati.',
      area: 'Guwahati',
      address: 'Guwahati, Assam',
      phone: '',
      website: 'https://mrnmrspet.com',
      websiteLabel: 'mrnmrspet.com',
      specialty: '5-Star Sitters, Insured, House Sitting, Daycare',
      badges: ['premium'],
      breeds: ['all']
    },
    {
      id: 'axomot-pets-sewa',
      rank: 5,
      name: 'Axomot Pets Sewa',
      city: 'assam',
      category: 'boarding',
      description: 'Home-based pet hotel in Guwahati offering personalized boarding. Bookable via PetBacker with insurance and 24\u00D77 support for complete peace of mind.',
      area: 'Guwahati',
      address: 'Guwahati, Assam',
      phone: '',
      website: 'https://petbacker.in',
      websiteLabel: 'PetBacker',
      specialty: 'Home-Based Pet Hotel, Insured',
      badges: ['at-home'],
      breeds: ['all']
    },
    {
      id: 'basisthapur-byelane-boarding',
      rank: 6,
      name: 'Basisthapur Byelane Boarding',
      city: 'assam',
      category: 'boarding',
      description: 'Dispur-area pet boarding with an excellent 4.8 star rating across 74 reviews. Also offers grooming services alongside comfortable boarding facilities.',
      area: 'Dispur, Guwahati',
      address: 'Basisthapur Byelane, Dispur, Guwahati',
      phone: '',
      website: 'https://justdial.com',
      websiteLabel: 'Justdial',
      specialty: 'Boarding + Grooming, 4.8 Rating',
      badges: ['award'],
      breeds: ['all']
    },
    {
      id: 'bhetapara-chariali-boarding',
      rank: 7,
      name: 'Bhetapara Chariali Boarding',
      city: 'assam',
      category: 'boarding',
      description: 'Dog hostel near Bhetapara Chariali with a perfect 5.0 star rating across 45 reviews. A highly-rated local favourite for reliable, caring dog boarding in Guwahati.',
      area: 'Bhetapara, Guwahati',
      address: 'Bhetapara Chariali, Guwahati',
      phone: '',
      website: 'https://justdial.com',
      websiteLabel: 'Justdial',
      specialty: 'Dog Hostel, 5.0 Rating',
      badges: ['award'],
      breeds: ['all']
    },

    /* --------------------------------------------------------
       PET FOOD STORES / PET SHOPS — ASSAM
       -------------------------------------------------------- */
    {
      id: 'kute-pets',
      rank: 1,
      name: 'Kute Pets',
      city: 'assam',
      category: 'petfood',
      description: "Assam's most loved pet food store and full-service animal care centre. In-store doctors with years of expertise provide diagnostic tests, dental workups, vaccines, deworming, and microchipping.",
      area: 'Guwahati',
      address: 'Guwahati, Assam',
      phone: '',
      website: 'https://kutepets.biz',
      websiteLabel: 'kutepets.biz',
      specialty: 'Pet Food + Full Vet Services, Microchipping',
      badges: ['premium'],
      breeds: ['all']
    },
    {
      id: 'pet-city-guwahati',
      rank: 2,
      name: 'Pet City',
      city: 'assam',
      category: 'petfood',
      description: 'Jatia Kahilipara Road store with years of experience selling puppies, aquariums, exotic birds, pet food, accessories, and offering grooming and veterinary clinic services.',
      area: 'Kahilipara, Guwahati',
      address: 'Jatia Kahilipara Road, near Ganesh Mandir, Guwahati',
      phone: '',
      website: 'https://5bestincity.com',
      websiteLabel: '5bestincity',
      specialty: 'Puppies, Aquariums, Birds, Food, Grooming, Vet',
      badges: [],
      breeds: ['all', 'puppy']
    },
    {
      id: 'paws-and-claws-assam',
      rank: 3,
      name: 'Paws And Claws Pet Store And Clinic',
      city: 'assam',
      category: 'petfood',
      description: 'One of the most renowned pet shops on Beltola-Basistha Road. Stocks various breeds of household animals and birds, along with a comprehensive range of pet food, accessories, and grooming.',
      area: 'Beltola-Basistha Road, Guwahati',
      address: 'Beltola-Basistha Road, Guwahati',
      phone: '',
      website: 'https://5bestincity.com',
      websiteLabel: '5bestincity',
      specialty: 'Pets, Birds, Food, Accessories, Grooming',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'goswami-kennel',
      rank: 4,
      name: 'Goswami Kennel',
      city: 'assam',
      category: 'petfood',
      description: 'Popular pet lifestyle store offering a variety of pets and accessories with expert advice from specialists. Stocks puppies, exotic birds, pet food, and provides clinic, grooming, and training services.',
      area: 'Guwahati',
      address: 'Guwahati, Assam',
      phone: '',
      website: 'https://5bestincity.com',
      websiteLabel: '5bestincity',
      specialty: 'Puppies, Birds, Expert Advice, Training',
      badges: [],
      breeds: ['all', 'puppy']
    },
    {
      id: 'amazing-pets-guwahati',
      rank: 5,
      name: 'Amazing Pets',
      city: 'assam',
      category: 'petfood',
      description: 'Leading pet and animal shop with a mission to provide the healthiest, happiest, well-socialized pets. Stocks veterinary foods, pet accessories, and offers grooming services.',
      area: 'Guwahati',
      address: 'Guwahati, Assam',
      phone: '',
      website: 'https://5bestincity.com',
      websiteLabel: '5bestincity',
      specialty: 'Healthy Pets, Vet Foods, Accessories, Grooming',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'max-vet-clinic-pet-store',
      rank: 6,
      name: 'Max Veterinary Clinic Pet Store',
      city: 'assam',
      category: 'petfood',
      description: 'Complete pet store integrated within the Max Veterinary Clinic. Stocks all kinds of pet accessories and a variety of pet food brands — the convenience of a shop alongside expert vet care.',
      area: 'Khanapara, Guwahati',
      address: 'Dutta Building, G.S. Road, Khanapara, Guwahati-22',
      phone: '',
      website: 'https://maxvetclinic.com',
      websiteLabel: 'maxvetclinic.com',
      specialty: 'Pet Store + Vet Clinic, All Brands',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'zoo-road-tinali-pet-shop',
      rank: 7,
      name: 'Zoo Road Tinali Pet Shop',
      city: 'assam',
      category: 'petfood',
      description: 'Well-known pet shop at Zoo Road Tinali with a 4.3 star rating across 779 reviews. Offers live pets and a range of pet supplies.',
      area: 'Zoo Road Tinali, Guwahati',
      address: 'Zoo Road Tinali, Guwahati',
      phone: '',
      website: 'https://justdial.com',
      websiteLabel: 'Justdial',
      specialty: 'Pets, Pet Supplies, 779 Reviews',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'mc-road-barowari-pet-shop',
      rank: 8,
      name: 'MC Road Barowari Pet Shop',
      city: 'assam',
      category: 'petfood',
      description: 'MC Road pet shop with 4.1 rating across 471 reviews. Offers live pets, pet food, and general pet care products — a reliable local favourite.',
      area: 'MC Road, Guwahati',
      address: 'MC Road, Barowari, Guwahati',
      phone: '',
      website: 'https://justdial.com',
      websiteLabel: 'Justdial',
      specialty: 'Pets, Food, Pet Care, 471 Reviews',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'interpet-fresh-pet-meals',
      rank: 9,
      name: 'INTERPET Fresh Pet Meals',
      city: 'assam',
      category: 'petfood',
      description: 'Fresh pet meals delivery service in Guwahati. Meals are freshly cooked using human-grade ingredients, packed hygienically, and stay fresh for up to 4 days. A healthier alternative to kibble.',
      area: 'Guwahati (Delivery)',
      address: 'Guwahati, Assam (delivery service)',
      phone: '',
      website: 'https://interpet.in',
      websiteLabel: 'interpet.in',
      specialty: 'Fresh Cooked Meals, Human-Grade, Delivery',
      badges: ['organic', 'at-home'],
      breeds: ['all']
    },

    /* ========================================================
       ========================================================
       BANGALORE — ALL CATEGORIES
       ========================================================
       ======================================================== */

    /* --------------------------------------------------------
       VETERINARY CLINICS / HOSPITALS — BANGALORE
       -------------------------------------------------------- */
    {
      id: 'cessna-lifeline',
      rank: 1,
      name: 'Cessna Lifeline Veterinary Hospital',
      city: 'bangalore',
      category: 'vets',
      description: 'Performed India\'s first permanent pacemaker implant in a dog. Founded by Dr. Pawan Kumar in 2002, this NABL-certified hospital specializes in hemodialysis, oncology, heart surgeries, and 24\u00D77 emergency care with a team of 40+ professionals.',
      area: 'Domlur, Bangalore',
      address: 'HBCS, 148, KGA Rd, Amarjyoti Layout, Domlur, Bangalore 560071',
      phone: '',
      website: 'https://cessnalifeline.com',
      websiteLabel: 'cessnalifeline.com',
      specialty: 'Pacemaker, Hemodialysis, Oncology, Heart Surgery, NABL Certified',
      badges: ['247', 'emergency', 'certified', 'premium'],
      breeds: ['all']
    },
    {
      id: 'bangalore-pet-hospital',
      rank: 2,
      name: 'Bangalore Pet Hospital',
      city: 'bangalore',
      category: 'vets',
      description: 'Founded by Dr. Shashank S in 2003, combining advanced diagnostic facilities with a compassionate team. Highly appreciated for dental, ophthalmic, and orthopedic services.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://bangalorepethospital.com',
      websiteLabel: 'bangalorepethospital.com',
      specialty: 'Dental, Ophthalmic, Orthopedic, Advanced Diagnostics',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'jeeva-pet-hospital',
      rank: 3,
      name: 'Jeeva Pet Hospital',
      city: 'bangalore',
      category: 'vets',
      description: 'Founded by Dr. Nagesh Reddy in 2004 with over 20 years of experience. Two branches in JP Nagar and Kanakpura offering comprehensive veterinary care across South Bangalore.',
      area: 'JP Nagar, Bangalore',
      address: '1360, 9th Cross Rd, opp. Rajshekar Hospital, Jeewan Sathi Colony, 1st Phase, J.P. Nagar, Bengaluru 560078',
      phone: '',
      website: 'https://jeevapethospital.com',
      websiteLabel: 'jeevapethospital.com',
      specialty: '20+ Years, Two Branches (JP Nagar, Kanakpura)',
      badges: ['multi-location'],
      breeds: ['all']
    },
    {
      id: 'vcare-pet-polyclinic',
      rank: 4,
      name: 'V-Care Pet Polyclinic',
      city: 'bangalore',
      category: 'vets',
      description: 'Multi-location polyclinic in Sarjapur, Koramangala, and Whitefield offering vaccinations, surgeries, grooming, and boarding services. Your pet can even have their own staycation.',
      area: 'Sarjapur / Koramangala / Whitefield',
      address: 'Sarjapur, Koramangala, Whitefield, Bangalore',
      phone: '',
      website: 'https://vcarepetpolyclinic.com',
      websiteLabel: 'vcarepetpolyclinic.com',
      specialty: 'Vaccinations, Surgeries, Grooming, Boarding',
      badges: ['multi-location'],
      breeds: ['all']
    },
    {
      id: 'crown-vet-bangalore',
      rank: 5,
      name: 'Crown Vet Hospital',
      city: 'bangalore',
      category: 'vets',
      description: 'Advanced veterinary clinic providing comprehensive medical and surgical facilities with highly qualified doctors and trainers on staff.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://crownvet.in',
      websiteLabel: 'crownvet.in',
      specialty: 'Advanced Medical & Surgical Facilities',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'sks-vet-hospital',
      rank: 6,
      name: 'SKS Veterinary Hospital',
      city: 'bangalore',
      category: 'vets',
      description: 'Premier veterinary establishment in Indiranagar offering exceptional pet healthcare, professional grooming, and short-term boarding. Features play areas, comfortable kennels, and individualized care plans.',
      area: 'Indiranagar, Bangalore',
      address: 'Indiranagar, Bangalore',
      phone: '',
      website: 'https://skspethospital.com',
      websiteLabel: 'skspethospital.com',
      specialty: 'Healthcare, Grooming, Short-Term Boarding, Play Areas',
      badges: ['premium'],
      breeds: ['all']
    },
    {
      id: 'precise-pet-clinic',
      rank: 7,
      name: 'Precise Pet Clinic & Diagnostics',
      city: 'bangalore',
      category: 'vets',
      description: 'Indiranagar-based clinic offering advanced diagnostics for precise, accurate pet healthcare. Trusted by local pet parents for thorough diagnostic workups.',
      area: 'Indiranagar, Bangalore',
      address: 'Indiranagar, Bangalore',
      phone: '',
      website: 'https://justdial.com',
      websiteLabel: 'Justdial',
      specialty: 'Advanced Diagnostics',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'cupa-small-animal-hospital',
      rank: 8,
      name: 'CUPA Small Animal Specialty Hospital',
      city: 'bangalore',
      category: 'vets',
      description: 'Cutting-edge hospital in RT Nagar with certified staff. Full range of services: consultations, grooming, sterilization, vaccinations, X-ray, ultrasound, ECG, blood tests, surgeries, trauma care, pet shop, and pharmacy.',
      area: 'RT Nagar, Bangalore',
      address: 'RT Nagar, Bangalore',
      phone: '',
      website: 'https://cupabangalore.org',
      websiteLabel: 'cupabangalore.org',
      specialty: 'Full-Service Hospital, X-Ray, ECG, Surgery, Pharmacy',
      badges: ['certified'],
      breeds: ['all']
    },
    {
      id: 'the-pet-practice',
      rank: 9,
      name: 'The Pet Practice',
      city: 'bangalore',
      category: 'vets',
      description: 'Launched in 2018 by Dr. Rishika Jain, known for a holistic pet wellness approach and modern facilities. Praised for gentle handling, dental care, and preventive medicine.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://justdial.com',
      websiteLabel: 'Justdial',
      specialty: 'Holistic Wellness, Dental Care, Preventive Medicine',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'paws-claws-clinic-blr',
      rank: 10,
      name: 'Paws and Claws Pet Clinic',
      city: 'bangalore',
      category: 'vets',
      description: 'Established medical clinic in Basaveshwar Nagar offering complete checkups with top certified doctors. Also stocks pet accessories and foods alongside medical treatment services.',
      area: 'Basaveshwar Nagar, Bangalore',
      address: 'Basaveshwar Nagar, Bangalore',
      phone: '',
      website: 'https://justdial.com',
      websiteLabel: 'Justdial',
      specialty: 'Complete Checkups, Pet Accessories & Food',
      badges: ['certified'],
      breeds: ['all']
    },

    /* --------------------------------------------------------
       DOG TRAINERS — BANGALORE
       -------------------------------------------------------- */
    {
      id: 'dogguru',
      rank: 1,
      name: 'DogGuru (Dr. Amrut Sridhara Hiranya)',
      city: 'bangalore',
      category: 'trainers',
      description: "India's only certified dog behaviourist from UNITEC New Zealand. Consultant to Railway Protection Force for 7+ years and Karnataka State Police advisor (2018\u20132021). Conducts CRPF classes. Trained 1,500+ dogs in 10 years.",
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://dogguru.in',
      websiteLabel: 'dogguru.in',
      specialty: 'Certified Behaviourist, Police K9, 1500+ Dogs Trained',
      badges: ['certified', 'award'],
      breeds: ['all', 'large', 'aggressive']
    },
    {
      id: 'pawspace-trainer',
      rank: 2,
      name: 'PawSpace',
      city: 'bangalore',
      category: 'trainers',
      description: 'Certified trainers conducting sessions tailored to your dog\u2019s behaviour, breed, and needs. Customised, kind approach with positive reinforcement. Skip crowded classes for personalised attention. Also offers cage-free boarding and healthy pet meals.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://pawspace.in',
      websiteLabel: 'pawspace.in',
      specialty: 'Personalised Sessions, Positive Reinforcement',
      badges: ['certified'],
      breeds: ['all', 'puppy']
    },
    {
      id: 'kuddle-trainer',
      rank: 3,
      name: 'Kuddle',
      city: 'bangalore',
      category: 'trainers',
      description: 'Passionate pet lovers with years of experience. Covers command training, house manners, socialization, guard training, and potty training. App-based booking. 10,000+ happy customers across 50+ Bangalore locations.',
      area: 'Bangalore (50+ locations)',
      address: 'Bangalore',
      phone: '',
      website: 'https://kuddle.pet',
      websiteLabel: 'kuddle.pet',
      specialty: 'App-Based, 10K+ Customers, 50+ Locations',
      badges: ['multi-location'],
      breeds: ['all', 'puppy']
    },
    {
      id: 'anand-k9-training',
      rank: 4,
      name: 'Anand K9 Training Centre',
      city: 'bangalore',
      category: 'trainers',
      description: 'Founded by Anand Gowda, certified expert cynologist with 25+ years of experience. Highly recommended by veterinarians. Offers group training, puppy training, and specialty programs with modern equipment.',
      area: 'Banashankari 2nd Block, Bangalore',
      address: 'Banashankari 2nd Block, Bangalore',
      phone: '',
      website: '',
      websiteLabel: '',
      specialty: '25+ Years, Cynologist, Vet-Recommended, Modern Equipment',
      badges: ['certified', 'award'],
      breeds: ['all', 'large', 'puppy']
    },
    {
      id: 'dog-obedience-training-blr',
      rank: 5,
      name: 'Dog Obedience Training',
      city: 'bangalore',
      category: 'trainers',
      description: 'Mr. Anil has built a solid reputation over 3+ years for gentle, effective training. 1,000+ happy clients. Makes the learning process fun for your furry child. Based in JP Nagar.',
      area: 'JP Nagar, Bangalore',
      address: 'JP Nagar, Bangalore',
      phone: '',
      website: 'https://dog-obedience-training.business.site',
      websiteLabel: 'dog-obedience-training.business.site',
      specialty: 'Gentle & Effective, 1000+ Happy Clients',
      badges: [],
      breeds: ['all', 'puppy']
    },
    {
      id: 'dogs-can-do-it',
      rank: 6,
      name: 'Dogs Can Do It (Vaibhav Mungole)',
      city: 'bangalore',
      category: 'trainers',
      description: 'Dog behaviour consultant firm and training centre. Provides pet parents a full 101 on why pets behave the way they do, how they interact with situations, and effective solutions.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: '',
      websiteLabel: '',
      specialty: 'Behaviour Consulting, Root-Cause Analysis',
      badges: [],
      breeds: ['all', 'aggressive']
    },
    {
      id: 'alpha8-trainer',
      rank: 7,
      name: 'Alpha8',
      city: 'bangalore',
      category: 'trainers',
      description: 'Over 5 years providing high-quality dog training and rehabilitation programs. Focuses on building a strong bond between dog and owner through structured, progressive training.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://starofservice.in',
      websiteLabel: 'StarOfService',
      specialty: 'Training & Rehabilitation, Owner-Dog Bonding',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'tata-steel-k9-trainer',
      rank: 8,
      name: 'Tata Steel K9 Squad Trainer',
      city: 'bangalore',
      category: 'trainers',
      description: 'Experienced professional whose last posting was heading the Tata Steel K9 Squad. Specialized in training all breeds with particular expertise in Malinois. One of India\'s top Malinois handlers. Results guaranteed.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://starofservice.in',
      websiteLabel: 'StarOfService',
      specialty: 'K9 Squad Experience, Malinois Specialist, All Breeds',
      badges: ['certified'],
      breeds: ['all', 'large', 'aggressive']
    },

    /* --------------------------------------------------------
       PET GROOMERS — BANGALORE
       -------------------------------------------------------- */
    {
      id: 'pawspace-groomer',
      rank: 1,
      name: 'PawSpace',
      city: 'bangalore',
      category: 'groomers',
      description: 'Book online, pick your time slot, and groomers arrive at your doorstep. Trusted by 1,700+ Google reviews (4.8\u2605). Professional process tailored to your pet\u2019s needs with clean tools and pet-safe products.',
      area: 'Bangalore (5 Cities)',
      address: 'Bangalore',
      phone: '',
      website: 'https://pawspace.in/pet-grooming',
      websiteLabel: 'pawspace.in',
      specialty: 'Doorstep Grooming, 4.8\u2605, 1700+ Reviews',
      badges: ['at-home', 'award'],
      breeds: ['all']
    },
    {
      id: 'thepetnest-groomer-blr',
      rank: 2,
      name: 'ThePetNest',
      city: 'bangalore',
      category: 'groomers',
      description: 'Expert groomers across Jayanagar, Koramangala, HSR Layout, Indiranagar, Malleshwaram, Whitefield, and Sarjapur Road. Book in-home grooming all 7 days. Background-checked groomers with 2+ years experience.',
      area: 'Multiple Areas, Bangalore',
      address: 'Jayanagar, Koramangala, HSR Layout, Indiranagar, Whitefield, Sarjapur',
      phone: '',
      website: 'https://thepetnest.com/pet-grooming/bangalore',
      websiteLabel: 'thepetnest.com',
      specialty: 'In-Home, 7-Day Booking, Background-Checked',
      badges: ['at-home', 'certified', 'multi-location'],
      breeds: ['all']
    },
    {
      id: 'oh-my-pet-grooming-blr',
      rank: 3,
      name: 'Oh My Pet Grooming',
      city: 'bangalore',
      category: 'groomers',
      description: 'Leading doorstep grooming company in Bangalore. Full services include bath, haircut, nail clipping, ear cleaning, de-stress massage, paw massage, and tick/flea treatment add-on.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://ohmypetgrooming.in',
      websiteLabel: 'ohmypetgrooming.in',
      specialty: 'Doorstep Full Grooming, Massage, Tick & Flea',
      badges: ['at-home'],
      breeds: ['all']
    },
    {
      id: 'shevar-groomer',
      rank: 4,
      name: 'Shevar',
      city: 'bangalore',
      category: 'groomers',
      description: 'Favourite among doggie parents. Beyond regular sessions, offers dental scaling and relaxing massages \u2014 including Ayurvedic massages for pets with bone or joint problems.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'LBB',
      specialty: 'Dental Scaling, Ayurvedic & Healing Massages',
      badges: ['premium'],
      breeds: ['all']
    },
    {
      id: 'fuzzy-wuzzy',
      rank: 5,
      name: 'Fuzzy Wuzzy Pet Styling Studio',
      city: 'bangalore',
      category: 'groomers',
      description: 'Luxurious grooming studio offering customised grooming, aromatherapy rinses, and all standard services like bath, nail trimming, and ear cleaning. A spa-level experience for your pet.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'LBB',
      specialty: 'Luxury Grooming, Aromatherapy, Customised Styling',
      badges: ['premium'],
      breeds: ['all', 'small']
    },
    {
      id: 'the-dog-studio-pet-spa',
      rank: 6,
      name: 'The Dog Studio Pet Spa',
      city: 'bangalore',
      category: 'groomers',
      description: 'JP Nagar salon providing clean-up, haircuts, nail clips, conditioning, blow-dry, tick treatments, pedicures, and specialty massages (calming, healing, bug repellant, pain-relieving). Uses premium equipment and products.',
      area: 'JP Nagar, Bangalore',
      address: 'JP Nagar, Bangalore',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'LBB',
      specialty: 'Full Spa, Specialty Massages, Tick Treatments',
      badges: ['premium'],
      breeds: ['all']
    },
    {
      id: 'pawse-groomer',
      rank: 7,
      name: 'Pawse',
      city: 'bangalore',
      category: 'groomers',
      description: 'Boarding and daycare facility that also offers grooming services including regular or medicated bath, trimming, and nail cutting. Special herbal baths: methi, oatmeal, coconut oil, and neem oil.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'LBB',
      specialty: 'Herbal Baths (Methi, Oatmeal, Neem), Medicated',
      badges: ['organic'],
      breeds: ['all']
    },
    {
      id: 'kuddle-groomer',
      rank: 8,
      name: 'Kuddle',
      city: 'bangalore',
      category: 'groomers',
      description: 'At-home grooming via app-based scheduling. Convenient option for a quick bath, nail trim, or de-shedding session without leaving your house.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://kuddle.pet',
      websiteLabel: 'kuddle.pet',
      specialty: 'App-Based At-Home, Quick Grooming',
      badges: ['at-home'],
      breeds: ['all']
    },
    {
      id: 'woof-spa-blr',
      rank: 9,
      name: 'Woof Spa',
      city: 'bangalore',
      category: 'groomers',
      description: 'Emphasizes overall well-being with health-focused grooming, skin care treatments, and flea baths. Expert groomers trained in both grooming and pet care. Calming atmosphere with soothing music.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: '',
      websiteLabel: '',
      specialty: 'Wellness Grooming, Skin Care, Flea Baths, Calming Atmosphere',
      badges: ['premium'],
      breeds: ['all']
    },
    {
      id: 'pawlish-blr',
      rank: 10,
      name: 'Pawlish',
      city: 'bangalore',
      category: 'groomers',
      description: 'Best suited for pet parents who want spa-quality grooming. Their grooming services are among the best in Bangalore \u2014 a top-tier choice for discerning pet parents.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: '',
      websiteLabel: '',
      specialty: 'Spa-Quality Grooming, Premium Service',
      badges: ['premium'],
      breeds: ['all', 'small']
    },

    /* --------------------------------------------------------
       PET BOARDING / HOSTELS — BANGALORE
       -------------------------------------------------------- */
    {
      id: 'pawspace-boarding',
      rank: 1,
      name: 'PawSpace',
      city: 'bangalore',
      category: 'boarding',
      description: 'Leading boarding facility offering a home away from home. Cozy, clean accommodations with soft bedding and spacious resting areas. 24/7 surveillance, trained staff, and regular photo/message updates for pet parents.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://pawspace.in',
      websiteLabel: 'pawspace.in',
      specialty: '24/7 Surveillance, Regular Updates, Cozy Stays',
      badges: ['premium', '247'],
      breeds: ['all']
    },
    {
      id: 'thepetnest-boarding-blr',
      rank: 2,
      name: 'ThePetNest',
      city: 'bangalore',
      category: 'boarding',
      description: 'Leading pet care provider connecting owners with vetted sitters and boarders. Premium locations: Indiranagar, Koramangala, Whitefield, Jayanagar, HSR Layout, JP Nagar, Electronic City, Malleshwaram, Bellandur, Marathahalli, Sarjapur Road.',
      area: 'Multiple Premium Areas, Bangalore',
      address: 'Indiranagar, Koramangala, Whitefield, Jayanagar, HSR Layout + more',
      phone: '',
      website: 'https://thepetnest.com/pet-boarding/bangalore',
      websiteLabel: 'thepetnest.com',
      specialty: 'Vetted Sitters, 12+ Premium Locations',
      badges: ['multi-location', 'certified'],
      breeds: ['all']
    },
    {
      id: 'bow-meow',
      rank: 3,
      name: 'Bow Meow',
      city: 'bangalore',
      category: 'boarding',
      description: 'Most reputed dog boarding in Bangalore. Secure, nurturing, enriching environment. Keeps pet parents updated with photos, notes, and care summaries. Prioritizes comfort, safety, and fun.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://thebowmeow.com',
      websiteLabel: 'thebowmeow.com',
      specialty: 'Most Reputed, Photo Updates, Enriching Environment',
      badges: ['premium'],
      breeds: ['all']
    },
    {
      id: 'barks2beaks',
      rank: 4,
      name: 'Barks2Beaks',
      city: 'bangalore',
      category: 'boarding',
      description: 'Sprawling 17,000 sq ft facility in Banashankari. Private kennels, fresh home-cooked meals twice daily, and a 1,200 sq ft pet swimming pool. "Staff treats dogs like their own." One of few places welcoming cats and birds too.',
      area: 'Banashankari, Bangalore',
      address: 'Banashankari, Bangalore',
      phone: '',
      website: 'https://barks2beaks.com',
      websiteLabel: 'barks2beaks.com',
      specialty: '17,000 sq ft, Pet Pool, Home-Cooked Meals, Dogs/Cats/Birds',
      badges: ['premium'],
      breeds: ['all', 'large']
    },
    {
      id: 'kuddle-boarding',
      rank: 5,
      name: 'Kuddle',
      city: 'bangalore',
      category: 'boarding',
      description: 'Jayanagar-based platform integrating wellness, boarding, grooming, and veterinary care. Clean, calm, thoughtfully structured facility for all ages. App-based booking with live updates and full transparency.',
      area: 'Jayanagar, Bangalore',
      address: 'Jayanagar, Bangalore',
      phone: '',
      website: 'https://kuddle.pet',
      websiteLabel: 'kuddle.pet',
      specialty: 'App-Based, Wellness Integrated, All Ages',
      badges: [],
      breeds: ['all', 'puppy']
    },
    {
      id: 'our-world-of-dogs',
      rank: 6,
      name: 'Our World of Dogs',
      city: 'bangalore',
      category: 'boarding',
      description: 'Go-to sanctuary for East Bangalore pet parents in Budigere. Luxury boarding defined by immaculate cleanliness, solar-powered facilities, AC rooms, and CCTV-monitored spaces mimicking a calm home environment.',
      area: 'Budigere, East Bangalore',
      address: 'Budigere, Bangalore',
      phone: '',
      website: 'https://ourworldofdogs.in',
      websiteLabel: 'ourworldofdogs.in',
      specialty: 'Luxury, Solar-Powered, AC Rooms, CCTV, Stress-Free',
      badges: ['premium'],
      breeds: ['all']
    },
    {
      id: 'dognation',
      rank: 7,
      name: 'DogNation',
      city: 'bangalore',
      category: 'boarding',
      description: 'HSR Layout / Bellandur powerhouse for holistic dog care. Spacious, dynamic facility designed for dogs who love to move, explore, and interact.',
      area: 'HSR Layout / Bellandur, Bangalore',
      address: 'HSR Layout / Bellandur, Bangalore',
      phone: '',
      website: 'https://dognation.pet',
      websiteLabel: 'dognation.pet',
      specialty: 'Holistic Care, Spacious, Active Dogs',
      badges: [],
      breeds: ['all', 'large']
    },
    {
      id: 'paw-palace',
      rank: 8,
      name: 'Paw Palace',
      city: 'bangalore',
      category: 'boarding',
      description: 'JP Nagar facility where structure meets softness. Spacious enclosures, individualized routines, empathetic handlers. Offers grooming, event-based playtimes, and transport facilities.',
      area: 'JP Nagar, Bangalore',
      address: 'JP Nagar, Bangalore',
      phone: '',
      website: 'https://pawpalace.in',
      websiteLabel: 'pawpalace.in',
      specialty: 'Individualized Routines, Transport, Grooming',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'play-pet-boarding',
      rank: 9,
      name: 'Play Pet Boarding',
      city: 'bangalore',
      category: 'boarding',
      description: 'Premium facility in North Bangalore (5km from MVIT intersection). Designed with animals in mind. Cat boarding "Purramid." Flexible daycare for working parents. Accepts dogs and cats.',
      area: 'North Bangalore (near Airport)',
      address: 'North Bangalore, 5km from MVIT intersection',
      phone: '',
      website: 'https://playpetboarding.com',
      websiteLabel: 'playpetboarding.com',
      specialty: 'Premium, Cat "Purramid", Flexible Daycare',
      badges: ['premium'],
      breeds: ['all']
    },
    {
      id: 'snouters',
      rank: 10,
      name: 'Snouters',
      city: 'bangalore',
      category: 'boarding',
      description: 'Home-based boarding connecting pet parents with the best homestays and trainers. Nutritious meals, walks, daycare. Strict no-chain policy with experienced, pet-loving caretakers.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://snouters.com',
      websiteLabel: 'snouters.com',
      specialty: 'Home-Based, No-Chain Policy, Nutritious Meals',
      badges: ['cage-free', 'at-home'],
      breeds: ['all']
    },
    {
      id: 'chippis-pet-boarding',
      rank: 11,
      name: "Chippi's Pet Boarding",
      city: 'bangalore',
      category: 'boarding',
      description: 'Varthur, Whitefield facility with dedicated professionals. Spacious areas for boarding and training with modern amenities, creating a safe, fun, stimulating environment.',
      area: 'Varthur, Whitefield, Bangalore',
      address: 'Varthur, Whitefield, Bangalore',
      phone: '',
      website: 'https://chippispetboarding.com',
      websiteLabel: 'chippispetboarding.com',
      specialty: 'Spacious, Training Integration, Modern Amenities',
      badges: [],
      breeds: ['all', 'large']
    },
    {
      id: 'benzi-pet-stay',
      rank: 12,
      name: 'Benzi Pet Stay',
      city: 'bangalore',
      category: 'boarding',
      description: "Farm-based boarding where pets can swim in the pool, jump through agility hoops, and explore terrain tracks. Kennel facilities for out-of-town travel. Features 'Ronnie\u2019s Happy Home' boarding enclosure.",
      area: 'Bangalore (Farm)',
      address: 'Bangalore',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'LBB',
      specialty: 'Farm, Swimming Pool, Agility Course, Terrain Tracks',
      badges: ['premium'],
      breeds: ['all', 'large']
    },

    /* --------------------------------------------------------
       PET FOOD STORES / PET SHOPS — BANGALORE
       -------------------------------------------------------- */
    {
      id: 'huft-bangalore',
      rank: 1,
      name: 'Heads Up For Tails (HUFT)',
      city: 'bangalore',
      category: 'petfood',
      description: '80+ expert pet spas and 250+ brands (2026 update). Wheelchair accessible. Huge collection for dogs, cats, birds, and fish. 95+ brands of toys, leashes, and personalised products. Multiple Bangalore stores including Magrath Road and Koramangala.',
      area: 'Multiple Locations, Bangalore',
      address: 'Magrath Road, Koramangala + more, Bangalore',
      phone: '',
      website: 'https://headsupfortails.com',
      websiteLabel: 'headsupfortails.com',
      specialty: '250+ Brands, 80+ Spas, Dogs/Cats/Birds/Fish',
      badges: ['premium', 'multi-location'],
      breeds: ['all']
    },
    {
      id: 'heavy-petting',
      rank: 2,
      name: 'Heavy Petting',
      city: 'bangalore',
      category: 'petfood',
      description: 'Family-operated business since 1932 (British Rule era) providing all breeds of dogs, cats, birds, and fish. Wide range of aquariums. Grooming services and same-day delivery. Staff genuinely care about the experience.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://5bestincity.com',
      websiteLabel: '5bestincity',
      specialty: 'Since 1932, All Pets, Aquariums, Same-Day Delivery',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'glenands',
      rank: 3,
      name: 'Glenands',
      city: 'bangalore',
      category: 'petfood',
      description: 'Go-to brand for all pet feed including dog biscuits. Stores offer leashes, beds, brushes, and products for hamsters, birds, and turtles. Exclusive grooming centre in Indiranagar.',
      area: 'Indiranagar + stores, Bangalore',
      address: 'Indiranagar, Bangalore',
      phone: '',
      website: 'https://glenands.com',
      websiteLabel: 'glenands.com',
      specialty: 'Pet Feed, Dog Biscuits, Grooming Centre, Multi-Pet',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'supertails-blr',
      rank: 4,
      name: 'Supertails',
      city: 'bangalore',
      category: 'petfood',
      description: 'Pet clinics + at-home services at your doorstep. 24-hour delivery in 24 cities. Stocks everything from prescription diets to toys and beds. State-of-the-art Supertails Clinics for check-ups, vaccinations, surgeries, and diagnostics.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://supertails.com',
      websiteLabel: 'supertails.com',
      specialty: '24hr Delivery, Pet Clinics, Prescription Diets',
      badges: ['at-home', 'multi-location'],
      breeds: ['all']
    },
    {
      id: 'dogmycats',
      rank: 5,
      name: 'DogMyCats',
      city: 'bangalore',
      category: 'petfood',
      description: 'Stocks for cats, dogs, guinea pigs, hamsters, rabbits, and birds. Food to grooming essentials plus travel accessories for pet vacations. Same-day delivery on orders before noon.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://dogmycats.com',
      websiteLabel: 'dogmycats.com',
      specialty: 'Multi-Pet, Travel Accessories, Same-Day Delivery',
      badges: ['at-home'],
      breeds: ['all']
    },
    {
      id: 'harshitha-pet-shop',
      rank: 6,
      name: 'Harshitha Pet Shop',
      city: 'bangalore',
      category: 'petfood',
      description: '20-year-old Bengaluru pet shop with a huge store stocking top brands: Purina, Pedigree, Royal Canin, Kennel D, Whiskas. Dry, canned, and frozen foods plus treats, belts, chains, and cages.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://5bestincity.com',
      websiteLabel: '5bestincity',
      specialty: '20+ Years, Top Brands, Dry/Canned/Frozen Foods',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'pet-choice-blr',
      rank: 7,
      name: 'Pet Choice',
      city: 'bangalore',
      category: 'petfood',
      description: 'Well-known store offering quality pet food, accessories, toys, grooming products, and daily essentials. Known for friendly service, clean environment, and commitment to responsible pet care.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://threebestrated.in',
      websiteLabel: 'threebestrated.in',
      specialty: 'Quality Food, Accessories, Friendly Service',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'ellas-petscape',
      rank: 8,
      name: "Ella's Petscape",
      city: 'bangalore',
      category: 'petfood',
      description: 'Doggy parent\u2019s dream \u2014 a space hosting a play area and lounge while your pooch gets royal treatment. Pet store with clinic, grooming centre, and animal behaviour specialist. Medication, food, accessories, toys, jumpers, and t-shirts for dogs.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://lbb.in',
      websiteLabel: 'LBB',
      specialty: 'Play Area + Lounge, Clinic, Behaviour Specialist, Dog Clothing',
      badges: ['premium'],
      breeds: ['all']
    },
    {
      id: 'pet-essentials-blr',
      rank: 9,
      name: 'Pet Essentials',
      city: 'bangalore',
      category: 'petfood',
      description: 'Jayanagar 4th Block one-stop destination serving the area for years. Friendly, knowledgeable staff. Pet accessories, food, grooming, daycare. Cages, food bowls, kennels for dogs, cats, rabbits, and birds.',
      area: 'Jayanagar 4th Block, Bangalore',
      address: 'Jayanagar 4th Block, Bangalore',
      phone: '',
      website: 'https://sulekha.com',
      websiteLabel: 'Sulekha',
      specialty: 'One-Stop Shop, Multi-Pet, Daycare, Grooming',
      badges: [],
      breeds: ['all']
    },
    {
      id: 'house-of-paws-blr',
      rank: 10,
      name: 'House of Paws',
      city: 'bangalore',
      category: 'petfood',
      description: 'Deals in all leading brands of pet food, treats, toys, and accessories. Driven by love for animals to serve the best to pets. A reliable neighbourhood destination.',
      area: 'Bangalore',
      address: 'Bangalore',
      phone: '',
      website: 'https://sulekha.com',
      websiteLabel: 'Sulekha',
      specialty: 'Leading Brands, Food, Treats, Toys, Accessories',
      badges: [],
      breeds: ['all']
    }

  ]; // end LISTINGS

  /* =========================================================
     BADGE METADATA
     Maps badge keys to display labels and CSS class suffixes
     ========================================================= */
  var BADGES = {
    '247':            { label: '24/7',           cls: 'badge-247' },
    'emergency':      { label: 'Emergency',      cls: 'badge-emergency' },
    'premium':        { label: 'Premium',        cls: 'badge-premium' },
    'at-home':        { label: 'At-Home',        cls: 'badge-at-home' },
    'cage-free':      { label: 'Cage-Free',      cls: 'badge-cage-free' },
    'budget':         { label: 'Budget',         cls: 'badge-budget' },
    'certified':      { label: 'Certified',      cls: 'badge-certified' },
    'mobile':         { label: 'Mobile',         cls: 'badge-mobile' },
    'award':          { label: 'Award-Winning',  cls: 'badge-award' },
    'organic':        { label: 'Organic',        cls: 'badge-organic' },
    'multi-location': { label: 'Multi-Location', cls: 'badge-multi-location' }
  };

  /* =========================================================
     PUBLIC API
     ========================================================= */
  return {
    CATEGORIES: CATEGORIES,
    BREED_TAGS:  BREED_TAGS,
    CITIES:      CITIES,
    LISTINGS:    LISTINGS,
    BADGES:      BADGES
  };

})();
